name: Run Pygame Acceptance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_acceptance_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libgtk-3-0 \
            libnotify-dev \
            libgconf-2-4 \
            libnss3 \
            libxss1 \
            libasound2 \
            xauth \
            x11-utils

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pygame pyautogui

      - name: Run Xvfb
        run: |
          Xvfb :99 &  # Start X virtual framebuffer to emulate display

      - name: Run acceptance tests
        env:
          DISPLAY: ":99.0"  # Set DISPLAY to use Xvfb
        run: |
          python -m unittest discover -s tests/acceptance_tests -p "*.py"

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: acceptance_test_screenshot.png
